### ISSUE TITLE
Put image carousel on the site's front page

### ISSUE THREAD

**Issue by taylorchenca** [kaiwahour/kaiwahour.github.io#1]
Image carousel of what's happening at Kaiwa hour on the front page. 

Criteria
- Admin needs to add, remove, replace photos easily
- Viewer will find the carousel visually pleasing, nice to look at

**Comment by captainalan** [comment]
I'm going to migrate this issue to the `home` repo;
https://github.com/kaiwahour/home
sorry its a bit confusing, it has to do with deployment & GitHub pages stuff
