### ISSUE TITLE
Put Twitter panel on the front page displaying latest tweet from official Twitter account

### ISSUE THREAD

**Issue by taylorchenca** [kaiwahour/kaiwahour.github.io#2]

**Comment by captainalan** [comment]
By "Twitter panel" here, do we mean a widget provided Twitter?

**Comment by taylorchenca** [comment]
Yes. That's what I have in mind. 
What do you think?

**Comment by captainalan** [comment]
Sounds good—I'll look into this;
I'll see if anybody has already built a decent looking Twitter component, otherwise it might be a cool thing to build from scratch

**Comment by captainalan** [comment]
Implemented https://github.com/kaiwahour/home/commit/82b3468fb2f729824d0b308f2e7bd18e4d0c2d2c
